poll:
  question: Which pet would you like to adopt?
  choices:
    - Dog
    - Cat
    - Parrot
    - Rabbit
  images:
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/main/dog.jpg
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/main/cat.jpg
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/main/parrot.jpg
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/main/rabbit.jpg
