poll:
  question: Which pet would you like to adopt?
  choices:
    - Dog
    - Cat
    - Parrot
    - Rabbit
  images:
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/ffe17bbaac87043dd27a5ef1ae1a56d511407adb/dog.jpg
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/master/cat.jpg
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/master/parrot.jpg
    - https://raw.githubusercontent.com/odedia/cloudnativepoll-config/refs/heads/master/rabbit.jpg
